### ISSUE TITLE
BuildError: Could not build url for endpoint 'bower.static'

### ISSUE THREAD

**Issue by Undo1** [VRGhost/PyPush#13]
When trying to run in PyBlueZ mode, I'm getting the following error:

```
root@my-VirtualBox:/home/me/Desktop/PyPush# ./bin/serve.sh --ble_driver pybluez --ble_device hci0  web_ui

2017-06-23 14:14:36,637 main              line:74   INFO     ====== PyPush is starting =====
2017-06-23 14:14:36,646 main              line:78   INFO     ===== App created =====
2017-06-23 14:14:37,089 _internal         line:87   INFO      * Running on http://localhost:5000/ (Press CTRL+C to quit)
2017-06-23 14:14:45,798 _internal         line:87   INFO     127.0.0.1 - - [23/Jun/2017 14:14:45] "GET /microbots HTTP/1.1" 404 -
2017-06-23 14:14:51,419 _internal         line:87   INFO     127.0.0.1 - - [23/Jun/2017 14:14:51] "GET /microbot HTTP/1.1" 404 -
[2017-06-23 14:14:54,903] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "PyPush/web/views.py", line 227, in index
    'index.html',
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/parker/Desktop/PyPush/PyPush/web/templates/index.html", line 11, in top-level template code
    <script src="{{ url_for('bower.static', filename='angular/angular.min.js') }}"></script>
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'bower.static' with values ['filename']. Did you mean 'static' instead?
2017-06-23 14:14:54,913 _internal         line:87   INFO     127.0.0.1 - - [23/Jun/2017 14:14:54] "GET / HTTP/1.1" 500 -
^C2017-06-23 14:15:50,792 main              line:84   INFO     ====== PyPush terminated ======
root@my-VirtualBox:/home/me/Desktop/PyPush# 
```

Any thoughts?

**Comment by Undo1** [comment]
Turns out I needed to install Angular with Bower.
