### ISSUE TITLE
Exception: No 'hci0' in 'Devices:\n'

### ISSUE THREAD

**Issue by javaftper** [VRGhost/PyPush#9]
Thanks for library.

All installed fine.  

Run "sudo ./bin/serve.sh --ble_driver pybluez --ble_device hci0  web_ui"

Receive-

` 
2017-05-19 19:45:55,587 main              line:74   INFO     ====== PyPush is starting =====
2017-05-19 19:45:55,598 main              line:81   ERROR    Top-level exception
Traceback (most recent call last):
  File "PyPush/main.py", line 77, in main
    app = create_app(args)
  File "PyPush/main.py", line 62, in create_app
    mbHub = PyPush.lib.main.create(args.debug, core.getPairDb(), args)
  File "PyPush/lib/main.py", line 34, in create
    raise Exception("No {!r} in {!r}".format(dev, out))
Exception: No 'hci0' in 'Devices:\n'
2017-05-19 19:45:55,600 main              line:84   INFO     ====== PyPush terminated ======
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/Downloads/PyPush-master/PyPush/__main__.py", line 6, in <module>
    PyPush.main.main(sys.argv[1:])
  File "PyPush/main.py", line 77, in main
    app = create_app(args)
  File "PyPush/main.py", line 62, in create_app
    mbHub = PyPush.lib.main.create(args.debug, core.getPairDb(), args)
  File "PyPush/lib/main.py", line 34, in create
    raise Exception("No {!r} in {!r}".format(dev, out))
Exception: No 'hci0' in 'Devices:\n'
`

Any thoughts?

**Comment by Mak601** [comment]
Looks like you don't have bluetooth device (hci0).

**Comment by javaftper** [comment]
My microbot (hci0) is next to my pi.  It's working via the IOS app.
Do I need to update a settings/config file etc with my microbot's mac address?

**Comment by WhistleMaster** [comment]
hci0 is your bluetooth dongle, not your microbot. You need a BLE capable dongle.

**Comment by javaftper** [comment]
I've got https://www.raspberrypi.org/products/raspberry-pi-3-model-b/ which has built in bluetooth with BLE support and it is enabled on my pi.

Thanks

**Comment by WhistleMaster** [comment]
Then you need to install the BLE libraries:
```bash
$ sudo apt-get install libdbus-1-dev libdbus-glib-1-dev libglib2.0-dev libical-dev libreadline-dev libudev-dev libusb-dev glib2.0 bluetooth bluez libbluetooth-dev
```
The command `hciconfig` will show your dongle (hci0):
```bash
$ sudo hciconfig hci0 up
```
You should be able to discover peripheral around you. To check it, do `sudo hcitool lescan` and if it shows you a list of surrounding BLE devices, it works fine. If not, do `sudo apt-get install bluez` and try again.

**Comment by javaftper** [comment]
Thanks.

Sorted now with those libraries.

i also needed to `sudo apt-get install libboost-python-dev` to get gattlib to install properly.

**Comment by VRGhost** [comment]
Thank you for resolving this. Apologies for not being of much help at the moment.

I've added this dependency to the comment in `bluez.txt`
